### ISSUE TITLE
Refactor app to use the `vonage` gem for Number Insight API calls

### ISSUE THREAD

**Issue by bencgreenberg** [nexmo-community/sinatra-caller-id#1]
This application uses the [Vonage Number Insight API](https://developer.nexmo.com/number-insight/overview), but does so making the HTTP call directly instead of using the [Vonage Ruby SDK](https://github.com/vonage/vonage-ruby-sdk). 

The application should use the SDK for the API calls.

Bonus: Add tests to validate the success of the refactor! 🌟

**Comment by exegete46** [comment]
@bencgreenberg I'm curious about the POST route to `/nexmo_insights`.  Is that referenced somewhere else that it should be maintained?

**Comment by exegete46** [comment]
Ok, I feel like I understand this a bit better.  That POST route was intended to act as a callback from the Vonage API.  I was unable to see the action due to testing on localhost.

Would it make more sense to send a text message as the callback rather than email?

**Comment by bencgreenberg** [comment]
Hey @exegete46, good question! I think let's leave the functionality as it is to keep the demo as it was created. Another demo that uses SMS though sounds like a good idea for a new project!

**Comment by exegete46** [comment]
@bencgreenberg Understandable.  I threw together a different branch if you find a use for it:  https://github.com/exegete46/sinatra-caller-id/tree/sms
